// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AResult: typeof import('ant-design-vue/es')['Result']
    Create: typeof import('./src/components/Create.vue')['default']
    Open: typeof import('./src/components/Open.vue')['default']
    Recent: typeof import('./src/components/Recent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Start: typeof import('./src/components/Start.vue')['default']
  }
}
